export const todosMunicipios = [
  'Rodrigues Alves',
  'Cruzeiro do Sul',
  'Tarauacá',
  'Jordão',
  'Feijó',
  'Brasiléia',
  'Plácido de Castro',
  'Marechal Thaumaturgo',
  'Pão de Açúcar',
  'Quebrangulo',
  'Poço das Trincheiras',
  'Marechal Deodoro',
  'Cacimbinhas',
  'São Sebastião',
  'Craíbas',
  'Maceió',
  'Major Isidoro',
  'Dois Riachos',
  'Carneiros',
  'Cajueiro',
  'Mata Grande',
  'Igaci',
  'Roteiro',
  'Maribondo',
  'Maragogi',
  'Monteirópolis',
  'Penedo',
  'Maravilha',
  'Batalha',
  'Lagoa da Canoa',
  'Palmeira dos Índios',
  'Junqueiro',
  'Teotônio Vilela',
  'Girau do Ponciano',
  'Inhapi',
  'Santana do Ipanema',
  "Olho d'Água do Casado",
  "Olho d'Água das Flores",
  'Carauari',
  'Eirunepé',
  'Barcelos',
  'Lábrea',
  'Coari',
  'Nova Olinda do Norte',
  'Manaus',
  'Alvarães',
  'Manacapuru',
  'Tefé',
  'Fonte Boa',
  'Juruá',
  'Humaitá',
  'Tapauá',
  'Novo Aripuanã',
  'Careiro',
  'Porto Velho',
  'Novo Airão',
  'Uarini',
  'Itacoatiara',
  'Barreirinha',
  'Parintins',
  'São Paulo de Olivença',
  'Ananindeua',
  'Macapá',
  'Santana',
  'Mazagão',
  'Tartarugalzinho',
  'Breves',
  'Belém',
  'Rafael Jambeiro',
  'Ribeira do Pombal',
  'Souto Soares',
  'Curaçá',
  'Cansanção',
  "Dias d'Ávila",
  'Feira de Santana',
  'Sento Sé',
  'Guanambi',
  'Cafarnaum',
  'Coração de Maria',
  'Teixeira de Freitas',
  'Wanderley',
  'Filadélfia',
  'Pindobaçu',
  'Banzaê',
  'Nova Soure',
  'Salvador',
  'Barrocas',
  'América Dourada',
  'Presidente Jânio Quadros',
  'Simões Filho',
  'São Desidério',
  'Valença',
  'Gavião',
  'Jacobina',
  'Jaguaquara',
  'Presidente Tancredo Neves',
  'Irecê',
  'Aporá',
  'Conde',
  'São Sebastião do Passé',
  'Jussara',
  'Pilão Arcado',
  'João Dourado',
  'Queimadas',
  'Maragogipe',
  'Botuporã',
  'Ponto Novo',
  'Lamarão',
  'Presidente Dutra',
  'Vila Velha',
  'Porto Seguro',
  'Guajeru',
  'Iuiu',
  'Piritiba',
  'Lapão',
  'São Gabriel',
  'Lençóis',
  'Serra do Ramalho',
  'Piraí do Norte',
  'Paramirim',
  'Ibitiara',
  'Maracás',
  'Seabra',
  'Santa Luzia',
  'Ourolândia',
  'Paratinga',
  'Rio do Pires',
  'Ibititá',
  'Brumado',
  'Tanhaçu',
  'Caraíbas',
  'Ibirapitanga',
  'Eunápolis',
  'Dom Basílio',
  'Itajuípe',
  'Itabela',
  'Macaúbas',
  'Bom Jesus da Serra',
  'Biritinga',
  'Jaguarari',
  'Tucano',
  'Pintadas',
  'São Félix do Coribe',
  'Vitória da Conquista',
  'Itamaraju',
  'Uauá',
  'Mirante',
  'Cotegipe',
  'Buerarema',
  'Wenceslau Guimarães',
  'Jandaíra',
  'Gandu',
  'Ibiassucê',
  'São Gonçalo dos Campos',
  'Rio de Contas',
  'Macururé',
  'Lajedo do Tabocal',
  'Cristópolis',
  'Angra dos Reis',
  'Canarana',
  'Candiba',
  'Santana do Acaraú',
  'Hidrolândia',
  'Croatá',
  'São Benedito',
  'Forquilha',
  'Amontada',
  'Várzea Alegre',
  'Reriutaba',
  'Maranguape',
  'Campos Sales',
  'Baturité',
  'Itapipoca',
  'Jaguaribe',
  'Pereiro',
  'Caucaia',
  'Iracema',
  'Russas',
  'Viçosa do Ceará',
  'Ipueiras',
  'Jijoca de Jericoacoara',
  'Itaitinga',
  'Marco',
  'Aratuba',
  'Fortaleza',
  'Milagres',
  'Groaíras',
  'Massapê',
  'São Gonçalo do Amarante',
  'Ererê',
  'Barro',
  'Santa Quitéria',
  'Varjota',
  'Quixeramobim',
  'Banabuiú',
  'Ocara',
  'Aracati',
  'Aiuaba',
  'Morada Nova',
  'Monsenhor Tabosa',
  'Ipu',
  'Tamboril',
  'Assaré',
  'Granja',
  'Brasília',
  'Itarana',
  'Afonso Cláudio',
  'Serra',
  'São Mateus',
  'Pedro Canário',
  'Vitória',
  'Cachoeiro de Itapemirim',
  'Aracruz',
  'Santa Maria de Jetibá',
  'Domingos Martins',
  'Linhares',
  'Cariacica',
  'Alegre',
  'Santa Teresa',
  'Iúna',
  'Vila Valério',
  'Muniz Freire',
  'Marilândia',
  'Muqui',
  'Águia Branca',
  'Marataízes',
  'Santa Leopoldina',
  'Itapemirim',
  'Guarapari',
  'Manhuaçu',
  'Mantenópolis',
  'Itaperuna',
  'Viana',
  'Venda Nova do Imigrante',
  'São Roque do Canaã',
  'Barra de São Francisco',
  'Colatina',
  'Jaguaré',
  'Guaçuí',
  'Iconha',
  'Ponto Belo',
  'Ibatiba',
  'Jerônimo Monteiro',
  'Rio Bananal',
  'São Gabriel da Palha',
  'Nova Venécia',
  'Israelândia',
  'Palestina de Goiás',
  'Palmeiras de Goiás',
  'Paraúna',
  'São Luís de Montes Belos',
  'Planaltina',
  'Piranhas',
  'Cavalcante',
  'Quirinópolis',
  'Caturaí',
  'Maurilândia',
  'São Miguel do Araguaia',
  'Silvânia',
  'Paranaiguara',
  'Pires do Rio',
  'Indiara',
  'Águas Lindas de Goiás',
  'Teresina de Goiás',
  'Itauçu',
  'Aragoiânia',
  'Inhumas',
  'Itapaci',
  'Cumari',
  'Palmelo',
  'Goianésia',
  'Goiânia',
  'Goianira',
  'Crixás',
  'Luziânia',
  'Formosa',
  'Gameleira de Goiás',
  'Cabeceiras',
  'Estrela do Norte',
  'Posse',
  'Jataí',
  'Mara Rosa',
  'Edéia',
  'Pirenópolis',
  'Guarani de Goiás',
  'Amorinópolis',
  'Novo Gama',
  'Catalão',
  'Abadiânia',
  'Porangatu',
  'Chapadão do Céu',
  'São João da Paraúna',
  'Minaçu',
  'Anhanguera',
  'Caldas Novas',
  'Mineiros',
  'Iporá',
  'Americano do Brasil',
  'Montividiu',
  'Turilândia',
  'Caxias',
  'Turiaçu',
  'São Luís',
  'Anajatuba',
  'Bequimão',
  'Timon',
  'Cururupu',
  'Pedro do Rosário',
  'Santa Rita',
  'Pinheiro',
  'Balsas',
  'Coroatá',
  'Araguaína',
  'Santa Inês',
  'Imperatriz',
  'Codó',
  'Anapurus',
  'Pará de Minas',
  'Pouso Alegre',
  'Caldas',
  'Varginha',
  'Igaratinga',
  'Ponte Nova',
  'Manhumirim',
  'São Gonçalo do Pará',
  'Reduto',
  'Bom Despacho',
  'Monte Santo de Minas',
  'Prata',
  'Itanhomi',
  'Belo Horizonte',
  'Nova Serrana',
  'Poços de Caldas',
  'Mutum',
  'Cruzília',
  'Ribeirão das Neves',
  'Alto Jequitibá',
  'Fervedouro',
  'Dom Joaquim',
  'Mateus Leme',
  'Itueta',
  'Aimorés',
  'Pedra Azul',
  'Camanducaia',
  'Itabira',
  'Inimutaba',
  'Berilo',
  'Nova Era',
  'Espera Feliz',
  'Campos Gerais',
  'Iraí de Minas',
  'Sarzedo',
  'Arceburgo',
  'Guaranésia',
  'Carmésia',
  'Ubá',
  'Ipatinga',
  'Itamonte',
  'Jequitinhonha',
  'Iapu',
  'Coronel Fabriciano',
  'Itamogi',
  'Visconde do Rio Branco',
  'Baldim',
  'Conselheiro Pena',
  'Bicas',
  'Curvelo',
  'Brasília de Minas',
  'Juvenília',
  'Além Paraíba',
  'Várzea da Palma',
  'Papagaios',
  'Prudente de Morais',
  'Resplendor',
  'Medina',
  'Juiz de Fora',
  'Barbacena',
  'Cachoeira de Minas',
  'Governador Valadares',
  'Água Boa',
  'Santo Hipólito',
  'Chapada Gaúcha',
  'Faria Lemos',
  'Viçosa',
  'Conceição de Ipanema',
  'Carmópolis de Minas',
  'Conceição do Mato Dentro',
  'Riachinho',
  'Monte Azul',
  'Teófilo Otoni',
  'Varzelândia',
  'Tapira',
  'Indaiabira',
  'Itapeva',
  'Caputira',
  'Moeda',
  'Carmo do Rio Claro',
  'Urucuia',
  'Januária',
  'Ibirité',
  'Francisco Badaró',
  'Uberlândia',
  'Novo Oriente de Minas',
  'Luisburgo',
  'Joanésia',
  'Itaúna',
  'Itatiaiuçu',
  'Coromandel',
  'Buritis',
  'Martins Soares',
  'Carmo de Minas',
  'Dom Bosco',
  'Campo Belo',
  'Itajubá',
  'Córrego Fundo',
  'Oratórios',
  'Contagem',
  'Santa Bárbara',
  'São Sebastião do Paraíso',
  'Cláudio',
  'Águas Formosas',
  'Santa Rita do Sapucaí',
  'Franciscópolis',
  'Nova União',
  'Simonésia',
  'Piranguinho',
  'Juruaia',
  'São Tiago',
  'Iturama',
  'Tombos',
  'Botelhos',
  'Betim',
  'Engenheiro Caldas',
  'Campina Verde',
  'Santana da Vargem',
  'Felixlândia',
  'Ponto dos Volantes',
  'Passos',
  'Divino',
  'Nanuque',
  'Montes Claros',
  'Perdigão',
  'Entre Rios de Minas',
  'Santa Cruz de Minas',
  'Caraí',
  'Dom Cavati',
  'Passa Tempo',
  'Sem-Peixe',
  'São José do Alegre',
  'Bom Repouso',
  'Raposos',
  'Vicentina',
  'Nioaque',
  'Tacuru',
  'Ivinhema',
  'Três Lagoas',
  'Nova Andradina',
  'Anastácio',
  'Coronel Sapucaia',
  'Taquarussu',
  'Juara',
  'Lucas do Rio Verde',
  'Peixoto de Azevedo',
  'Guarantã do Norte',
  'Tangará da Serra',
  'Nova Maringá',
  'Marcelândia',
  'Brasnorte',
  'Rondonópolis',
  'Santo Antônio do Leste',
  'Alto Taquari',
  'Várzea Grande',
  'Curvelândia',
  'Colíder',
  'Confresa',
  'Juína',
  'Aripuanã',
  'Cuiabá',
  'Diamantino',
  'Sinop',
  'Sapezal',
  'Nova Canaã do Norte',
  'Poconé',
  'Dom Aquino',
  'Palmas',
  'Porto Estrela',
  'Nova Bandeirantes',
  'São José do Povo',
  'Cotriguaçu',
  'Nova Xavantina',
  'Abaetetuba',
  'Santarém',
  'Pacajá',
  'Curralinho',
  'Bagre',
  'Garrafão do Norte',
  'São Sebastião da Boa Vista',
  'Limoeiro do Ajuru',
  'Cametá',
  'Tucuruí',
  'São Domingos do Capim',
  'Castanhal',
  'Anajás',
  'Moju',
  'Irituia',
  'Muaná',
  'Ponta de Pedras',
  'Cachoeira do Arari',
  'Salvaterra',
  'Benevides',
  'Barcarena',
  'Marituba',
  'Oriximiná',
  'Oeiras do Pará',
  'Igarapé-Miri',
  'Santa Izabel do Pará',
  'Capitão Poço',
  'Aurora do Pará',
  'Conceição do Araguaia',
  'Ourilândia do Norte',
  'Altamira',
  'Bragança',
  'Salinópolis',
  'Capanema',
  'Augusto Corrêa',
  'Tailândia',
  'Afuá',
  'Acará',
  'Marabá',
  'Rondon do Pará',
  'Maracanã',
  'Juruti',
  'Curuçá',
  'Alenquer',
  'Canaã dos Carajás',
  'Água Azul do Norte',
  'Ulianópolis',
  'Melgaço',
  'Portel',
  'Bujaru',
  'Mocajuba',
  'Terra Alta',
  'Inhangapi',
  'São Francisco do Pará',
  'São Miguel do Guamá',
  'Itaituba',
  'São João de Pirabas',
  'Tomé-Açu',
  'Igarapé-Açu',
  'Ipixuna do Pará',
  'Paragominas',
  'Redenção',
  'Vigia',
  'Dom Eliseu',
  'Magalhães Barata',
  'Itupiranga',
  'Ourém',
  'Tracuateua',
  'Mãe do Rio',
  'Jacareacanga',
  'Baião',
  'Curuá',
  'Prainha',
  'Santarém Novo',
  'Parauapebas',
  'Colares',
  'Nova Timboteua',
  'Monte Alegre',
  'Novo Repartimento',
  'Concórdia do Pará',
  'Breu Branco',
  'Gurupá',
  'Mojuí dos Campos',
  'Rurópolis',
  'Juru',
  'Santana de Mangueira',
  'Guarabira',
  'Boqueirão',
  'Cabaceiras',
  'Camalaú',
  'Areia',
  'Arara',
  'Aroeiras',
  'Tavares',
  'Alagoa Grande',
  'Princesa Isabel',
  'Campina Grande',
  'Riacho de Santo Antônio',
  'João Pessoa',
  'São Bento',
  'Gurjão',
  'Uiraúna',
  'Bom Sucesso',
  'AÁgua Branca',
  'Itaporanga',
  'Santo André',
  'Casserengue',
  'Sumé',
  'Brejo dos Santos',
  'Amparo',
  'Juazeirinho',
  'Caturité',
  'Livramento',
  'Picuí',
  'Pedra Lavrada',
  'Pilar',
  'Lagoa de Dentro',
  'Natuba',
  'Pocinhos',
  'Belém do Brejo do Cruz',
  'Puxinanã',
  'Santana dos Garrotes',
  'Barra de Santana',
  'Santa Teresinha',
  'Bezerros',
  'Vertentes',
  'Recife',
  'São Joaquim do Monte',
  'São Caitano',
  'Altinho',
  'Abreu e Lima',
  'Vitória de Santo Antão',
  'Toritama',
  'Tupanatinga',
  'Panelas',
  'São Bento do Una',
  'Triunfo',
  'Garanhuns',
  'Venturosa',
  'Arcoverde',
  'Santa Cruz do Capibaribe',
  'Ipojuca',
  'Araripina',
  'Ibimirim',
  'Afrânio',
  'Pedra',
  'Serra Talhada',
  'São José do Egito',
  'Custódia',
  'Cabo de Santo Agostinho',
  'Sertânia',
  'Tacaratu',
  'Salgueiro',
  'Pedro II',
  'Ilha Grande',
  'Teresina',
  'Picos',
  'Piripiri',
  'Dom Inocêncio',
  'Jacobina do Piauí',
  'Acauã',
  'Oeiras',
  'Valença do Piauí',
  'Paquetá',
  'Novo Santo Antônio',
  'Santa Rosa do Piauí',
  'Floriano',
  'Santo Inácio do Piauí',
  'São João do Piauí',
  'Luís Correia',
  'São Raimundo Nonato',
  'Jaicós',
  'Patos do Piauí',
  'Beneditinos',
  'União da Vitória',
  'Pinhais',
  'Dois Vizinhos',
  'Matelândia',
  'Rio Azul',
  'Guamiranga',
  'Terra Roxa',
  'Castro',
  'Engenheiro Beltrão',
  'Campo Largo',
  'Leópolis',
  'Cornélio Procópio',
  'Turvo',
  'Carambeí',
  'Três Barras do Paraná',
  'Telêmaco Borba',
  'Curitiba',
  'Cianorte',
  'Fernandes Pinheiro',
  'Paranaguá',
  'Pato Branco',
  'Quatro Pontes',
  'Paula Freitas',
  'Balsa Nova',
  'Tijucas do Sul',
  'São João do Triunfo',
  'Flor da Serra do Sul',
  'Coronel Vivida',
  'Sengés',
  'Cafelândia',
  'São Carlos do Ivaí',
  'Faxinal',
  'Bituruna',
  'Verê',
  'Figueira',
  'São José dos Pinhais',
  'Lunardelli',
  "Pérola d'Oeste",
  'Bocaiúva do Sul',
  'Laranjeiras do Sul',
  'Francisco Beltrão',
  'Sulina',
  'Antonina',
  'Foz do Iguaçu',
  'Ponta Grossa',
  'Araucária',
  'Salto do Lontra',
  'Reserva',
  'Teixeira Soares',
  'Mallet',
  'Morretes',
  'São Mateus do Sul',
  'Santo Antônio do Sudoeste',
  'Medianeira',
  'Nova Londrina',
  'Tamboara',
  'Pinhão',
  'Laranjal',
  'Rio Bonito',
  'Rio das Ostras',
  'Nova Iguaçu',
  'Vassouras',
  'Rio de Janeiro',
  'São Fidélis',
  'Magé',
  'Teresópolis',
  'São Gonçalo',
  'Armação dos Búzios',
  'Quatis',
  'Macaé',
  'Maricá',
  'Três Rios',
  'Sumidouro',
  'Volta Redonda',
  'Porto Real',
  'Paraty',
  'Itaboraí',
  'Araruama',
  'Alexandria',
  'Janduís',
  'Currais Novos',
  'Portalegre',
  'Natal',
  'São João do Sabugi',
  'Tenente Ananias',
  'Marcelino Vieira',
  'Jardim de Piranhas',
  'Pilões',
  'Tangará',
  'Jardim do Seridó',
  'Jaçanã',
  'Mossoró',
  'Major Sales',
  'Carnaubais',
  'Pau dos Ferros',
  'Areia Branca',
  'Alto Paraíso',
  'Ariquemes',
  'Cacoal',
  'Candeias do Jamari',
  "Espigão D'Oeste",
  'Itapuã do Oeste',
  'Jaru',
  'Ji-Paraná',
  "Machadinho D'Oeste",
  'Pimenta Bueno',
  'Urupá',
  'Monte Negro',
  'Guajará-Mirim',
  "Alta Floresta D'Oeste",
  'Vale do Anari',
  'São Francisco do Guaporé',
  'Cujubim',
  'Campo Novo de Rondônia',
  'Nova Mamoré',
  'Costa Marques',
  'Theobroma',
  'Alto Alegre dos Parecis',
  'Rio Crespo',
  'Vale do Paraíso',
  'Boa Vista',
  'Caracaraí',
  'Mucajaí',
  'Tapera',
  'Lindolfo Collor',
  'Colinas',
  'Alvorada',
  'Capão da Canoa',
  'Salvador do Sul',
  'Erval Seco',
  'Seberi',
  'Lajeado',
  'Nova Santa Rita',
  'Canoas',
  'Pelotas',
  'Ivoti',
  'Osório',
  'Xangri-lá',
  'Cruz Alta',
  'Portão',
  'São Marcos',
  'Carazinho',
  'Ijuí',
  'Rio Grande',
  'Torres',
  'Marau',
  'Eugênio de Castro',
  'Gramado',
  'Presidente Lucena',
  'Cachoeirinha',
  'Garibaldi',
  'Mostardas',
  'Mato Leitão',
  'Redentora',
  'Montenegro',
  'Taquara',
  'Condor',
  'Picada Café',
  'Estância Velha',
  'Candelária',
  'Cotiporã',
  'Tenente Portela',
  'Lagoa Vermelha',
  'Pirapó',
  'Pinto Bandeira',
  'Tapejara',
  'Sarandi',
  'Imbituba',
  'Brusque',
  'Sombrio',
  'Porto Belo',
  'Schroeder',
  'Forquilhinha',
  'São José',
  'Lages',
  'Itapema',
  'Chapecó',
  'Riqueza',
  'Xanxerê',
  'Florianópolis',
  'São Miguel do Oeste',
  'Passos Maia',
  'Itajaí',
  'Criciúma',
  'Guaraciaba',
  'São Ludgero',
  'Nova Erechim',
  'Biguaçu',
  'Tubarão',
  'Balneário Piçarras',
  'Balneário Camboriú',
  'Araranguá',
  'Guabiruba',
  'Penha',
  'Ipumirim',
  'Sangão',
  'Indaial',
  'Caibi',
  'Videira',
  'Capivari de Baixo',
  'Lindóia do Sul',
  'Porto União',
  'Santo Amaro da Imperatriz',
  'Catanduvas',
  'Guatambú',
  'Salto Veloso',
  'Pinhalzinho',
  'Santa Helena',
  'Camboriú',
  'Joaçaba',
  'Ibirama',
  'Gravatal',
  'Neópolis',
  'Pacatuba',
  'São Cristóvão',
  'Porto da Folha',
  'Canindé de São Francisco',
  'Barra dos Coqueiros',
  'Aracaju',
  'Lagarto',
  "Itaporanga d'Ajuda",
  'Malhada dos Bois',
  'Nossa Senhora do Socorro',
  'Rubiácea',
  'Bertioga',
  'São Carlos',
  'Lorena',
  'Ibiúna',
  'Guarujá',
  'Porto Feliz',
  'Ilha Comprida',
  'São Paulo',
  'Nova Guataporanga',
  'Franca',
  'Indaiatuba',
  'Suzanápolis',
  'Peruíbe',
  'Santos',
  'São José da Bela Vista',
  'Mauá',
  'Cubatão',
  'Campinas',
  'Ferraz de Vasconcelos',
  'Praia Grande',
  'Guaiçara',
  'Promissão',
  'Araçatuba',
  'Campo Limpo Paulista',
  'Santa Gertrudes',
  'Santa Isabel',
  'Salto de Pirapora',
  'Saltinho',
  'Guarulhos',
  'Araguatins',
  "Pau D'Arco",
  'Miracema do Tocantins',
  'Colméia',
  'Palmeirópolis',
  'Novo Jardim',
  'Peixe',
  'Augustinópolis',
  'Paraíso do Tocantins',
  'Divinópolis do Tocantins',
  'São Bento do Tocantins',
  'Tocantinópolis',
  'Aparecida do Rio Negro',
  'Araguacema',
];

export const siglasEstados = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO',
  'DF',
];
